### PR TITLE
Expose possibleLengths from json, allow querying by country and phone number type

### PR DESCRIPTION
**Pull request by blwinters**
We are using this to assign a value to `PhoneNumberTextField.maxDigits`, based on the user's currently selected country code / region code. I'm more than happy to make adjustments and add tests for this pull request if the general functionality is of interest. Just let me know.

### CODE REVIEW

**Comment by xezero** [comment]
I would love to have this merged into this PR as I've been looking for this :)

**Comment by xezero** [comment]
This would be awesome if we could merge this! Been looking for this for a while!!

**Comment by kuyazee** [comment]
Hello, @blwinters can you rework your PR, this looks to be a great inclusion to PhoneNumberKit because of the recent pr #300

**Comment by blwinters** [comment]
Hey @kuyazee. Sorry for the delay, but I've finally reworked my PR. Please let me know if you have any questions or requests.

**Pull request merged**
