### PR TITLE
i18n of CountryCodePickerViewController

### PR DESCRIPTION
**Pull request by the0neyouseek**
Add `NSLocalizedString` for : 
- The title of the ViewController
- The "Current" keyword
- The "Common" keyword

### CODE REVIEW

**Comment by immortal79** [comment]
Any plan on merging this PR ? I would also be interested by this feature.

**Comment by isupremedyou** [comment]
@kuyazee, are you able to merge this PR?

**Comment by IVANKRUPSKI** [comment]
Hello!

Will NSLocalizedString be added for  "Choose your country" as well?
We would very much appreciate this.

Looking forward to the release.

**Comment by IVANKRUPSKI** [comment]
Hey guys!

Any chance this is going to be released soon?

Thanks!

**Comment by IVANKRUPSKI** [comment]
Hey guys!

Any chance this is going to be released soon?

Thanks!

**Pull request merged**
