### PR TITLE
Prepare for Swift 5 + Xcode 10.2 compatibility

### PR DESCRIPTION
**Pull request by florentmorin**
Tested with Xcode 10.2 beta 3 + Swift 4.2 / Swift 5

### CODE REVIEW

**Comment by nikolay-kapustin** [comment]
Less warnings = less pain!

**Comment by awall1** [comment]
@marmelroy can we get some love? 🥰

**Comment by twitterkb** [comment]
i see approval for these changes a day ago.  can this commit be merged?  would love to get rid of these warnings.

**Comment by twitterkb** [comment]
we are moving forward locally with this patch in our day-to-day development, but are still awaiting for it to be officially merged to the base marmelroy repo.

we are also moving forward locally with the patches in

- https://github.com/marmelroy/PhoneNumberKit/pull/273
- https://github.com/marmelroy/PhoneNumberKit/pull/274
- https://github.com/marmelroy/PhoneNumberKit/pull/275

two of which sit on top of this patch.

we will monitor here for the official merges.

thank you.

**Comment by liambutler-lawrence** [comment]
Left a comment in https://github.com/marmelroy/PhoneNumberKit/pull/275, but this PR seems to have more conversation so copying here... @marmelroy What needs to happen to get one of these PRs merged? We use your SDK in a framework we develop, and one of our clients has a zero-warnings policy in 3rd party SDKs.

**Comment by marmelroy** [comment]
Sorry for the delay with this. I've been away. I will invite more contributors as collaborators with merge rights.

**Pull request merged**
