### PR TITLE
adding region ID

### PR DESCRIPTION
**Pull request by vinnyt**
@marmelroy hopefully this is more in line.

### CODE REVIEW

**Comment by marmelroy** [comment]
Thanks @vinnyt - this is great. Can you also update the tests that are failing (see Travis build)?

**Comment by vinnyt** [comment]
@marmelroy tests fixed.

**Comment by vinnyt** [comment]
@marmelroy bump on this one?

**Comment by marmelroy** [comment]
Thanks @vinnyt, merging

**Pull request merged**
