### PR TITLE
Swift 3

### PR DESCRIPTION
**Pull request by davbeck**
I'm submitting this request to master, but I believe that there should be a swift-3 branch instead. What I would propose as the timeline would be:

1. Maintain 2.3 and 3.0 branches until Xcode 8 GM is released.
2. Keep the 2.3 branch long term for legacy support.
3. Merge 3.0 into master.
4. When the next version of Swift is released, create a legacy swift-3.0 branch off of master.

This way, user's of the framework can target a specific branch if they need legacy support, or master if they want the most current version.

Thoughts?

### CODE REVIEW

**Comment by marmelroy** [comment]
Thanks a lot @davbeck! I really appreciate you doing the migrating and proposing this action plan. 

On the surface, it all looks great.

I will however need to read through all the code before merging (and try and fix Travis, I think they have an Xcode 8 machine now). Also I want to check how other frameworks are handling the transition before making a decision.

**Comment by dmcgloin** [comment]
Thanks @davbeck and @marmelroy 

I have some questions regarding the change to remove the dispatch_once function in ParseOperation.swift. It looks like Swift 3 no longer allows using dispatch_once:

`.../PhoneNumberKit/ParseOperation.swift:133:9: 'dispatch_once' is unavailable in Swift: Use lazily initialized globals instead`

...and therefore a change was made to resolve this - which is good. This appears to be one of the few changes not automatically suggested by the Swift 3 Migrator tool.

However, I have 2 questions:

1. Do we think think the proposed change is safe? I haven't scrutinized the code, but it looks like the guarantees of dispatch_once have been removed in favor of a simplified state check.

2. For this specific change, if we think the proposed change is appropriate, can we roll that change into the master branch supporting Swift 2.2 (and implicitly Swift 2.3)?  It looks like code could be written to cross-compile in Swift 2.x and Swift 3.0.  This would greatly assist in smoothing out the transition phase while Xcode 8 is in beta.

Thanks again for the awesome work!

**Comment by davbeck** [comment]
`dispatch_once` shouldn't be used here regardless of what version of Swift is being used. From the documentation:

> **Declaration**
> `typedef long dispatch_once_t;`
> **Discussion**
> Variables of this type must have global or static scope. The result of using this type with automatic or dynamic allocation is undefined. See dispatch_once for details.

It has been a fairly common misuse of `dispatch_once` to use it to initialize or perform tasks once for a given object since the introduction of the API in ObjC. I'm guessing this is why it was deprecated in Swift 3, since most proper use cases for it are covered by global variable initialization (which uses `dispatch_once` when it is safe to do so and not using it when it isn't).

As far as the safety of the code otherwise, I haven't looked that closely at the operation. Generally `NSOperation`s do need to be thread safe because their properties are accessed from multiple queues when other operations depend on them. From what I could see, there was nothing in place to protect the rest of the code though. It wouldn't hurt to wrap access to the operations properties with either a serial dispatch queue or a mutex.

**Comment by marmelroy** [comment]
Thanks @davbeck and @dmcgloin. All fair points. 

When building PhoneNumberKit, some compromises were made in favour of a nicer syntax / friendlier API that reduced thread safety and were less than ideal as far as memory management is concerned. 

The more I'm thinking about it, the more I would like the Swift 3 version to be the mature, thread-safe v1.0 of PhoneNumberKit. Instead of just making the framework compile for Swift 3, the language update is a good excuse to also rethink the API and make significant improvements to the way PhoneNumberKit works under the hood.

**Comment by marmelroy** [comment]
Hi again @davbeck (and thanks @leoMehlig too)! I really appreciate the continuing updates. 

I took your PR and merged it into a new "swift 3.0" branch. 

As previously mentioned, the plan is to not just to do a translation but actually use the new release of Swift as an excuse for a new breaking version of PhoneNumberKit that resolves some of the remaining issues in the current version. The Swift 3.0 branch is where that development will take place.

**Pull request closed without merging**
