### PR TITLE
Metadata Update

### PR DESCRIPTION
**Pull request by the0neyouseek**
Update metadata to latest version

### CODE REVIEW

**Comment by twitterkb** [comment]
in reviewing this metadata update versus previous metadata updates, i notice that, e.g. @kuyazee also updated the version value in the .podspec .  i don't use pods, but does that have to happen here?

**Comment by the0neyouseek** [comment]
Hi @twitterkb,
Updating the version number in podspec would imply to publish a new release and as I’m not a maintainer I don’t feel like it’s my place to do in this PR.

**Comment by tiagoaap** [comment]
@twitterkb I'm kind in a rush to have the metadata updated without forking the lib 😢
Do you have any prediction of when a new release will drop out containing this?

Thanks bud

**Comment by the0neyouseek** [comment]
Hi @twitterkb I have rebased this commit if you want to take another look

**Comment by marmelroy** [comment]
Replaced by https://github.com/marmelroy/PhoneNumberKit/pull/407

**Pull request closed without merging**
