### PR TITLE
Swift 4

### PR DESCRIPTION
**Pull request by irace**
I can understand not wanting to merge this into `master` until Xcode 9 is out of beta – you may want to make a `swift-4` branch that can become the base branch for this PR?

### CODE REVIEW

**Comment by irace** [comment]
Also, I added a `fatalError` where I wasn’t sure how else to proceed, but as someone who knows this library much better than I, perhaps you have a better idea?

**Comment by irace** [comment]
@nikolay-kapustin I‘m not sure what you mean?

**Comment by nikolay-kapustin** [comment]
@irace oops so sorry, I'm writing comment inside commit fork page, not see pull request

**Comment by irace** [comment]
@nikolay-kapustin Hello! Any chance of merging?

**Comment by nikolay-kapustin** [comment]
@marmelroy Come on guys!

**Comment by brendan09** [comment]
Xcode 9 / Swift 4 is GM now. Any chance of this being merged soon?

**Comment by dpopov** [comment]
Just added another [4.0 branch](https://github.com/marmelroy/PhoneNumberKit/pull/164). This includes all of your changes with two adjustments:
I removed the superfluous `}.flatMap{$0}` in [PhoneNumberKit.swift](https://github.com/marmelroy/PhoneNumberKit/compare/master...dpopov:master#diff-a6842b8b66894d09fd0e5ab2f5c182eb) 
And where you used a guard/fail I give it default value of [start/end](https://github.com/marmelroy/PhoneNumberKit/compare/master...dpopov:master#diff-a4ba2779bea2ac3e787b79d4aedd77ad)

**Comment by marmelroy** [comment]
Merged https://github.com/marmelroy/PhoneNumberKit/pull/164

**Pull request closed without merging**
